### ISSUE TITLE
Stuck on the first time init or high volumn comments incoming.

### ISSUE THREAD

**Issue by NoahDragon** [NoahDragon/cat-generator-avatars#1] opened 2017-01-20 17:07 UTC
#### Version Information

* PHP:  7.0
* WordPress: 4.7.1 

#### Steps to Reproduce

1.  Leave many comments on a page
1.  Vanilla install the plugin
1.  Open that page on browsers

#### What I Expected

Open the page as usual and show cat avatars in discussion.

#### What Happened Instead

502 Gateway Error.

After server seconds, the error disappeared.

**Comment by NoahDragon** [comment] 2017-01-20 17:09
Assumption: the writing cache files process blocks the server to access.
Solution based on the assumption: async the cache file writing process.

**Comment by Jon007** [comment] 2017-04-09 08:46
You need a mystery cat avatar until everything is ready.
Although this error might have been issue connecting to gravatar.com as code was doing a call for each image to check for valid gravatar.
At least I was also getting some errors on initial activation which seem to be resolved now by taking out the gravatar call.

**Comment by NoahDragon** [comment] 2017-04-09 13:53
@Jon007 The issue is still persist, but much better than before. Thank you.

**Comment by Jon007** [comment] 2017-04-09 14:59
hmm yes, it's still quite bad, I just loaded in 25 users and it just displays 2 before getting stuck, 
that's unnaturally slow, and there's no CPU usage, what's going on?

It's hard to tell, but it seems like it kicks off creation of about 2 every time you go into the page before hanging....  from my 25 new users it has created about 15 in the last 30 minutes

**Comment by Jon007** [comment] 2017-04-09 16:20
things to try:

- [x] ~~switch to .png~~ with low compression to avoid any extra image manipulation tasks which can be slow: tried, `imagepng($monster, $savedfile, 0, PNG_NO_FILTER)` : so no conversion from png to jpg (as the source files are png), no compression, no filters:  still no real improvement, unacceptably slow/hanging

- [x] ~~pre-build the files~~ let me see  20x15x15x10x10 = 450,000 files = not an option

- [ ] switch to imagemagick to avoid painfully slow GD library eg: http://stackoverflow.com/questions/12661/efficient-jpeg-image-resizing-in-php

- [ ] threading.   in fact some of the imagemagick advice suggested to launch as separate process which is another alternative to threading.
Either way, what might need to happen is:
- if the cache file does not exist
  - launch a worker thread/process to build the file
  - return a pre-built mystery cat

**Comment by Jon007** [comment] 2017-04-09 17:07
ImageMagick has a specific composite command to compose multiple images into 1 which can be run as exec('composite 1.png 2.png'), according to research  "It's well documented, not bound to PHPs memory limits and the performance is ok"
I'm not sure how widely ImageMagick is installed - it's not on my MacBook but it appears to be already installed on my CentOS and other linux servers.

**Comment by NoahDragon** [comment] 2017-04-09 17:57
@Jon007 the multi-threading would be the best option. However, to enable the php sync option, it requires system settings. Similar to ImageMagick, not many people have turned the settings on in their php environment.

I'm also thinking to put the pre-build images on a public/CDN server, like the http://avatars.adorable.io/, and call api to retrieve them.

**Comment by Jon007** [comment] 2017-04-10 00:22
hmmm.... how about:

1.  use a flag to detect if currently making an image (maybe in fact make the class a singleton with static methods)
1.  if flag is currently on:
  - schedule WP CRON to make the image later
  - return mystery cat url

it's basic, but it wouldn't hang and at least WP CRON is available everywhere...

**Comment by Jon007** [comment] 2017-04-10 01:01
Also as the issue is really a problem on first activation or on bulk load of users, it could be addressed by adding a separate function to build the images, and having it kicked off asynchronously.   
wp-cron is a bad choice for long running jobs of course as it actually runs when a user is visiting the server, unless that's been turned off as per eg: https://www.lucasrolff.com/wordpress/why-wp-cron-sucks/

**Comment by Jon007** [comment] 2017-04-10 07:29
found the slow function:
imagefill is a known slow function, by commenting out this line, I got fairly ok perfomance cats on a black background:
`//imagefill($monster,0,0,$white);`
The recommended alternative is:
`imagefilledrectangle($monster, 0, 0, 256, 256, $white);
`
this gives a significant performance boost, along with the use of .png and avoiding conversion from .png to compressed jpg...    it's blazingly fast now, eg I set my users screen to display 40 users per page, delete all the cached files, refresh the page, it all loads and the cached files are all recreated with no delay.

**Closed as completed** 2017-04-10 08:19 UTC
Labels: bug

**Comment by NoahDragon** [comment] 2017-04-10 12:08
Thanks @Jon007 . I have published it to wordpress.

**Comment by Jon007** [comment] 2017-04-10 12:47
thanks @NoahDragon it's looking good!
